fix: fix  typo

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -214,7 +214,7 @@ jobs:
             sleep 15
 
             echo "Applying database migrations..."
-            sudo docker exec ${{ env.APP_CONTAINER_NAME }} pnpx prisma migrate deploy || { echo "Prisma migrate deploy failed!"; exit 1; }
+            sudo docker exec ${{ env.APP_CONTAINER_NAME }} npx prisma migrate deploy || { echo "Prisma migrate deploy failed!"; exit 1; }
 
             echo "Cleaning up old Docker images..."
             sudo docker image prune -af
